### ISSUE TITLE
Build on windows-latest is failing

### ISSUE THREAD

**Issue by martin-majlis** [nicledomaS/cmake_build_action#25]
**Describe the bug**

When this action is used on `windows-latest` it fails with `Start build: Error: Command failed: cmake --build . --config Release --parallel 2`

https://github.com/martin-majlis/probstructs/runs/1422657342?check_suite_focus=true

**To Reproduce**
1. Create a build workflow
2. Specify that it should be run-on: windows-latest
3. Trigger that workflow

**Expected behavior**

It should succeed and build a package.

**Additional context**
https://github.com/martin-majlis/probstructs/runs/1422657342?check_suite_focus=true

**Comment by nicledomaS** [comment]
I have investigated problem. I have added log to stdout. This should help you

**Comment by martin-majlis** [comment]
Thanks for fixing this.

However after upgrading to version 1.1 build for mac is failing - https://github.com/martin-majlis/probstructs/runs/1497465498 - so now it never gets to building package for Windows. :/

**Comment by nicledomaS** [comment]
Use this instruction: https://gitlab.kitware.com/cmake/community/-/wikis/doc/cpack/Packaging-With-CPack
I have added fix for packaging. https://github.com/marketplace/actions/build-c-project v1.2
I also recommend to use my template like example. https://github.com/nicledomaS/CppProjectTemplate
My successful result: https://github.com/nicledomaS/CppProjectTemplate/actions/runs/402597174

You need to pay attention to files: 
https://github.com/nicledomaS/CppProjectTemplate/blob/main/CMakeLists.txt 
```
install(TARGETS ${PROJECT_NAME} RUNTIME DESTINATION bin)

set(CPACK_GENERATOR TGZ)
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VENDOR "CMake.org")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "MyLib - CPack Component Installation Example")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "CPack Component Example")
SET(CPACK_NSIS_MODIFY_PATH ON)

include(CPack)
```
and https://github.com/nicledomaS/CppProjectTemplate/blob/main/.github/workflows/.github.yml
