### ISSUE TITLE
How to set CMake version?

### ISSUE THREAD

**Issue by chadananda** [nicledomaS/cmake_build_action#40]
Sorry, I'm new at this. I understand I need version 3.19.1 specifically. How to configure that?

**Comment by nicledomaS** [comment]
Hello.
You should install cmake version 3.19.1. Also you can sets the minimum required version of cmake for a project in CMakeLists.txt.

https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html

example:
```
cmake_minimum_required(VERSION 3.19.1) <--------- This is setting  minimum required version of cmake for a project

project(RemoteBinaryMapper)

set(CMAKE_CXX_STANDARD 17)

include(cmake/make.cmake)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -Wall")

include_directories(${CMAKE_SOURCE_DIR}/modules/common/include)

find_package(cpprestsdk REQUIRED)

executable(${PROJECT_NAME}
            SOURCES "./src"
            THREADS
            MODULES BinaryMapper)
```

**Comment by nicledomaS** [comment]
Hello @chadananda  
GitHub-hosted runners have a cmake version 3.21.4 on all OS and you shouldn't have any problems with action. 
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

If your project don't build on github then send it to me, I will check it. 
If you cannot build project locally then you need install cmake version 3.19.1 and more on your computer. 

Also I recommend to set the minimum required version of cmake for a project in CMakeLists.txt. 
https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html

example:
```
cmake_minimum_required(VERSION 3.19.1)    #<--------- This is setting minimum required version of cmake for a project

project(RemoteBinaryMapper)

set(CMAKE_CXX_STANDARD 17)

include(cmake/make.cmake)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -Wall")

include_directories(${CMAKE_SOURCE_DIR}/modules/common/include)

find_package(cpprestsdk REQUIRED)

executable(${PROJECT_NAME}
            SOURCES "./src"
            THREADS
            MODULES BinaryMapper)

```

**Comment by nicledomaS** [comment]
Hi @chadananda 
Do you have some problems with Action?
If you don't have problem I will close this issue.
